platform :ios, '9.0'

use_frameworks!

target 'MarkdownKit_Example' do
  pod 'MarkdownKit', :path => '../'

  target 'MarkdownKit_Tests' do
    inherit! :search_paths

  end
end


post_install do |installer|
    
    # https://github.com/CocoaPods/CocoaPods/issues/5521#issuecomment-226328062
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
end
